version: '3.1'

services:

    postgres:
        image: postgres
        container_name: postgres
        hostname: postgres
        restart: always
        env_file:
            - database.env
        ports:
            - 15432:5432
        networks:
            - postgres-networks

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        hostname: pgadmin4
        env_file:
            - database.env
        ports:
            - "18080:80"
        depends_on:
            - postgres
        networks:
            - postgres-networks

networks: 
    postgres-networks:
        driver: bridge