version: '3.1'
services:
  database:
    image: postgres
    container_name: database
    hostname: database
    restart: always
    env_file:
        - database.env
    ports:
        - 15432:5432
    volumes:
        - database-data:/var/lib/postgresql/data/